### ISSUE TITLE
Payment to bank account .us.$1700

### ISSUE THREAD

**Issue by coin750** [EdgeApp/airbitz-core-java#3]

**Comment by swansontec** [comment]
This appears to be spam.

**Comment by coin750** [comment]
http://chart.apis.google.com/chart?cht=qr&chs=324x324&chl=http%3A%2F%2Fwww.smartbit.com.au%2Fsending%241700usd%2Freceiver%3A++%0ABANK+NAME%3A+CITIBANK%0ABANK+ADDRESS%3A+225+W+VIRGINA+CRYSTAL+LAKE+IL+60014+USA%0AACCOUNT+NUMBER%3A+147361042%0AROUTING+NO%3A+271070801%0ASWIFT+CODE%3A+CITIUS33%0ABENEFICIARY+NAME%3A+LELAND+JEROME%0ABENEFICIARY+ADDRESS%3A+708+S.RIVESIDE.+DR+McHENRY+IL+.60050.USA%2Fsender%3AA.Gerta+Tomin
...........privkey:
92AFLN1yUadTjrwZxc6GqHM4JqYXeqonA3KEqZEyPxDeqijWe1P

Closed #3 <https://github.com/EdgeApp/airbitz-core-java/issues/3>.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/EdgeApp/airbitz-core-java/issues/3?email_source=notifications&email_token=ACUILF63AOV2XYQA36RRIETQ4TNXPA5CNFSM4KCLQ3CKYY3PNVWWK3TUL52HS4DFWZEXG43VMVCXMZLOORHG65DJMZUWGYLUNFXW5KTDN5WW2ZLOORPWSZGOV2JTVDA#event-2928884364>,
or unsubscribe

**Comment by peachbits** [comment]
@coin750 if you need support please use our contact form https://support.edge.app/support/tickets/new

**Comment by coin750** [comment]
Ask update- payment
id:994cb23c7b51e3d840903de6ac50064645dfd13ad4a5050312910231124db581..
..capacity:0,127 BTC
≈ 1 002,12 USD-
Payment-$950 to b.account.us.tx: by link:

http://chart.apis.google.com/chart?cht=qr&chs=324x324&chl=http%3A%2F%2Fwww.smartbit.com.au%2Fsend%24950usd+to%3A++NAME%3A+EGERUE+JOY%0A%0A14500+Dallas+Pkwy%2C+Dallas%2C+TX+75254%2C+United+States%0ABANK%3A+BANK+OF+AMERICA%0ABANK+ADDRESS%3A%C2%A014999+PRESTON+RD+DALLAS%2C+TEXAS+75254%0AROUTING+NO%3A+111000025%0A%0ASWIFT+CODE-BOFAUS3N%0AACCT%3A+488065279074%0A%0A%2Fsender%3A86......%40gmail.com

@coin750 <https://github.com/coin750> if you need support please use our
contact form https://support.edge.app/support/tickets/new

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/EdgeApp/airbitz-core-java/issues/3?email_source=notifications&email_token=ACUILFYWJWNSTIBK7XBMXDDQ4Y3N3A5CNFSM4KCLQ3CKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEIN5IIA#issuecomment-572249120>,
or unsubscribe

**Comment by swansontec** [comment]
@coin750 If you need help selling Bitcoin to a bank account, please contact our support department. We do not offer support on GitHub.
